### ISSUE TITLE
Header not found when missing "(" in the line

### ISSUE THREAD

**Issue by g23guy** [g23guy/sca-patterns-devel-security#6]
* SUSE Linux Enterprise High Performance Computing 15 SP2 LTSS 15-SP2
    (aarch64)
    * dpdk-thunderx-debugsource-19.11.4-150200.3.22.1
    * dpdk-thunderx-19.11.4-150200.3.22.1
    * dpdk-thunderx-kmp-default-debuginfo-19.11.4_k5.3.18_150200.24.142-150200.3.22.1
    * dpdk-thunderx-devel-debuginfo-19.11.4-150200.3.22.1
    * dpdk-thunderx-devel-19.11.4-150200.3.22.1
    * dpdk-thunderx-kmp-default-19.11.4_k5.3.18_150200.24.142-150200.3.22.1
    * dpdk-thunderx-debuginfo-19.11.4-150200.3.22.1

URI: https://lists.suse.com/pipermail/sle-security-updates/2023-March/014115.html

==> Processing package: SUSE Linux Enterprise High Performance Computing 15 SP2 LTSS 15-SP2
==> Packages parts: ['SUSE Linux Enterprise High Performance Computing 15 SP2 LTSS 15', 'SP2']
==> Processing package: (aarch64)
==> Packages parts: ['(aarch64)']
Traceback (most recent call last):
  File "/home/opt/scatools/sca-patterns-devel-security/bin/sagen", line 979, in <module>
    main(sys.argv)
  File "/home/opt/scatools/sca-patterns-devel-security/bin/sagen", line 946, in main
    security = SecurityAnnouncement(msg, dirbase, target_url, sa_file)
  File "/home/opt/scatools/sca-patterns-devel-security/bin/sagen", line 176, in __init__
    self.__get_package_lists()
  File "/home/opt/scatools/sca-patterns-devel-security/bin/sagen", line 301, in __get_package_lists
    self.__deconstruct_package(text)
  File "/home/opt/scatools/sca-patterns-devel-security/bin/sagen", line 259, in __deconstruct_package
    pkg_version = pkg_parts[-2] + '-' + pkg_parts[-1]
IndexError: list index out of range

**Comment by g23guy** [comment]
Fixed
