### ISSUE TITLE
List index out of range for 015131.html

### ISSUE THREAD

**Issue by g23guy** [g23guy/sca-patterns-devel-security#8]
URI: https://lists.suse.com/pipermail/sle-security-updates/2023-June/015131.html

\#############################################################################
\# Security Advisory Announcement Pattern Generator v2.0.6
\# for the SCA Tool
\#############################################################################
Processing single file    = 015131.html
Traceback (most recent call last):
  File "/usr/local/bin/sagen", line 1002, in <module>
    main(sys.argv)
  File "/usr/local/bin/sagen", line 969, in main
    security = SecurityAnnouncement(msg, dirbase, target_url, sa_file)
  File "/usr/local/bin/sagen", line 176, in __init__
    self.__get_package_lists()
  File "/usr/local/bin/sagen", line 311, in __get_package_lists
    if not self.__deconstruct_package(text):
  File "/usr/local/bin/sagen", line 261, in __deconstruct_package
    pkg_version = pkg_parts[-2] + '-' + pkg_parts[-1]
IndexError: list index out of range

**Comment by g23guy** [comment]
> Header:                =  * Server Applications Module 15-SP5 (noarch)
 >  Package:              = mariadb-errormessages-10.6.13-150400.3.23.1 => (4) ['mariadb', 'errormessages', '10.6.13', '150400.3.23.1']
 >  Package:              = Galera for Ericsson 15 SP4 (x86_64) => (1) ['Galera for Ericsson 15 SP4 (x86_64)']
Traceback (most recent call last):
  File "/usr/local/bin/sagen", line 1002, in <module>
    main(sys.argv)
  File "/usr/local/bin/sagen", line 969, in main
    security = SecurityAnnouncement(msg, dirbase, target_url, sa_file)
  File "/usr/local/bin/sagen", line 176, in __init__
    self.__get_package_lists()
  File "/usr/local/bin/sagen", line 311, in __get_package_lists
    if not self.__deconstruct_package(text):
  File "/usr/local/bin/sagen", line 261, in __deconstruct_package
    pkg_version = pkg_parts[-2] + '-' + pkg_parts[-1]
IndexError: list index out of range

**Comment by g23guy** [comment]
Galaria for Ericsson is not recognized as a new header.

**Comment by g23guy** [comment]
I will exclude package names with spaces.

**Comment by g23guy** [comment]
Fixed
